spring:
  mvc:
    dispatch-options-request: true
  datasource:
    url: jdbc:mysql://localhost:3306/payment?useSSL=false
    username: root
    password: root
#    url: jdbc:h2:mem:testdb;mode=mysql;INIT=CREATE SCHEMA IF NOT EXISTS PAYMENT AUTHORIZATION sa;DB_CLOSE_ON_EXIT=FALSE;
#    username: sa
#    password: ''
logging:
  level:
    com:
      company: INFO
    org:
      springframework: INFO
      h2: INFO
