server:
  port: 9100
  tomcat:
    protocol_header: x-forwarded-proto
    remote_ip_header: x-forwarded-for
    accesslog:
      enabled: true
      directory: /dev
      prefix: stdout
      buffered: false
      suffix: ''
      file-date-format: ''
spring:
  flyway:
    locations: classpath:db/order/migrations
    table: _schema_history
    schemas: order
  h2:
    console:
      enabled: true
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: order
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: true
